// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiRhs-nHnYkd2Uiz7FXTTkO0ohEGyWiVE',
    appId: '1:481989589642:web:312aa7e26c14b45fc34b73',
    messagingSenderId: '481989589642',
    projectId: 'eos-chatting-cf78d',
    authDomain: 'eos-chatting-cf78d.firebaseapp.com',
    storageBucket: 'eos-chatting-cf78d.appspot.com',
    measurementId: 'G-7RHJ97863D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTWgAzGY6Dg6ibrVExi3K-fIwiwwSs-5o',
    appId: '1:481989589642:android:9731d16cc7301e72c34b73',
    messagingSenderId: '481989589642',
    projectId: 'eos-chatting-cf78d',
    storageBucket: 'eos-chatting-cf78d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQ96iCUd1v-_MTAxyRI6kbH5xAuCGSs4',
    appId: '1:481989589642:ios:3e594425989c75b8c34b73',
    messagingSenderId: '481989589642',
    projectId: 'eos-chatting-cf78d',
    storageBucket: 'eos-chatting-cf78d.appspot.com',
    iosClientId: '481989589642-iip85k8b1amrubln2o20c3ipp4qv42ta.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
